source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'7.0'

pod 'Parse'
pod 'ParseUI'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'BZGFormField'
pod 'TSMessages'
pod 'SDWebImage'
pod 'FaceAwareFill'
pod 'Mantle'
pod 'pop'
pod 'BlocksKit'
pod 'RateView'
pod 'TOWebViewController'